{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "04199cbc-b74d-45f6-94b3-3271a5a6b12b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting dlib\n",
      "  Using cached dlib-19.24.6.tar.gz (3.4 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  python setup.py bdist_wheel did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [84 lines of output]\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py:234: SyntaxWarning: invalid escape sequence '\\('\n",
      "    major = re.findall(\"set\\(CPACK_PACKAGE_VERSION_MAJOR.*\\\"(.*)\\\"\", open(cmake_file).read())[0]\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py:235: SyntaxWarning: invalid escape sequence '\\('\n",
      "    minor = re.findall(\"set\\(CPACK_PACKAGE_VERSION_MINOR.*\\\"(.*)\\\"\", open(cmake_file).read())[0]\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py:236: SyntaxWarning: invalid escape sequence '\\('\n",
      "    patch = re.findall(\"set\\(CPACK_PACKAGE_VERSION_PATCH.*\\\"(.*)\\\"\", open(cmake_file).read())[0]\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_ext\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py:163: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "    if LooseVersion(cmake_version) < '3.1.0':\n",
      "  Building extension for Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\build\\lib.win-amd64-cpython-312 -DPYTHON_EXECUTABLE=C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\python.exe -DDLIB_USE_FFMPEG=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\build\\lib.win-amd64-cpython-312 -A x64'\n",
      "  -- Building for: NMake Makefiles\n",
      "  CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):\n",
      "    Compatibility with CMake < 3.10 will be removed from a future version of\n",
      "    CMake.\n",
      "  \n",
      "    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax\n",
      "    to tell CMake that the project requires at least <min> but has been updated\n",
      "    to work with policies introduced by <max> or earlier.\n",
      "  \n",
      "  \n",
      "  CMake Error at CMakeLists.txt:5 (message):\n",
      "  \n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "    You must use Visual Studio to build a python extension on windows.  If you\n",
      "    are getting this error it means you have not installed Visual C++.  Note\n",
      "    that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "    development.  You need to install Visual Studio for C++.\n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "  \n",
      "  \n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 2, in <module>\n",
      "    File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "    File \"C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py\", line 243, in <module>\n",
      "      setup(\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\__init__.py\", line 117, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 183, in setup\n",
      "      return run_commands(dist)\n",
      "             ^^^^^^^^^^^^^^^^^^\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 199, in run_commands\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 954, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\dist.py\", line 950, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\command\\bdist_wheel.py\", line 398, in run\n",
      "      self.run_command(\"build\")\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 316, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\dist.py\", line 950, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 135, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 316, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\dist.py\", line 950, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py\", line 168, in run\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-397aq1ic\\dlib_6f91328645db47f1ae57abcf3f561f3d\\setup.py\", line 206, in build_extension\n",
      "      subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\subprocess.py\", line 413, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\Kevin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-397aq1ic\\\\dlib_6f91328645db47f1ae57abcf3f561f3d\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\Kevin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-397aq1ic\\\\dlib_6f91328645db47f1ae57abcf3f561f3d\\\\build\\\\lib.win-amd64-cpython-312', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\Kevin\\\\anaconda3\\\\envs\\\\opencv_env\\\\python.exe', '-DDLIB_USE_FFMPEG=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\Kevin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-397aq1ic\\\\dlib_6f91328645db47f1ae57abcf3f561f3d\\\\build\\\\lib.win-amd64-cpython-312', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)\n"
     ]
    }
   ],
   "source": [
    "pip install dlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a1bda1cf-58c5-4816-a5bf-43ab7183eff1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl.metadata (21 kB)\n",
      "Collecting face-recognition-models>=0.3.0 (from face_recognition)\n",
      "  Using cached face_recognition_models-0.3.0-py2.py3-none-any.whl\n",
      "Collecting Click>=6.0 (from face_recognition)\n",
      "  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)\n",
      "Collecting dlib>=19.7 (from face_recognition)\n",
      "  Using cached dlib-19.24.6.tar.gz (3.4 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: numpy in c:\\users\\kevin\\anaconda3\\envs\\opencv_env\\lib\\site-packages (from face_recognition) (1.26.4)\n",
      "Requirement already satisfied: Pillow in c:\\users\\kevin\\anaconda3\\envs\\opencv_env\\lib\\site-packages (from face_recognition) (10.4.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\kevin\\anaconda3\\envs\\opencv_env\\lib\\site-packages (from Click>=6.0->face_recognition) (0.4.6)\n",
      "Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Using cached click-8.1.8-py3-none-any.whl (98 kB)\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  python setup.py bdist_wheel did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [84 lines of output]\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py:234: SyntaxWarning: invalid escape sequence '\\('\n",
      "    major = re.findall(\"set\\(CPACK_PACKAGE_VERSION_MAJOR.*\\\"(.*)\\\"\", open(cmake_file).read())[0]\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py:235: SyntaxWarning: invalid escape sequence '\\('\n",
      "    minor = re.findall(\"set\\(CPACK_PACKAGE_VERSION_MINOR.*\\\"(.*)\\\"\", open(cmake_file).read())[0]\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py:236: SyntaxWarning: invalid escape sequence '\\('\n",
      "    patch = re.findall(\"set\\(CPACK_PACKAGE_VERSION_PATCH.*\\\"(.*)\\\"\", open(cmake_file).read())[0]\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_ext\n",
      "  C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py:163: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "    if LooseVersion(cmake_version) < '3.1.0':\n",
      "  Building extension for Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\build\\lib.win-amd64-cpython-312 -DPYTHON_EXECUTABLE=C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\python.exe -DDLIB_USE_FFMPEG=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\build\\lib.win-amd64-cpython-312 -A x64'\n",
      "  -- Building for: NMake Makefiles\n",
      "  CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):\n",
      "    Compatibility with CMake < 3.10 will be removed from a future version of\n",
      "    CMake.\n",
      "  \n",
      "    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax\n",
      "    to tell CMake that the project requires at least <min> but has been updated\n",
      "    to work with policies introduced by <max> or earlier.\n",
      "  \n",
      "  \n",
      "  CMake Error at CMakeLists.txt:5 (message):\n",
      "  \n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "    You must use Visual Studio to build a python extension on windows.  If you\n",
      "    are getting this error it means you have not installed Visual C++.  Note\n",
      "    that there are many flavors of Visual Studio, like Visual Studio for C#\n",
      "    development.  You need to install Visual Studio for C++.\n",
      "  \n",
      "  \n",
      "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
      "  \n",
      "  \n",
      "  \n",
      "  \n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 2, in <module>\n",
      "    File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "    File \"C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py\", line 243, in <module>\n",
      "      setup(\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\__init__.py\", line 117, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 183, in setup\n",
      "      return run_commands(dist)\n",
      "             ^^^^^^^^^^^^^^^^^^\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\core.py\", line 199, in run_commands\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 954, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\dist.py\", line 950, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\command\\bdist_wheel.py\", line 398, in run\n",
      "      self.run_command(\"build\")\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 316, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\dist.py\", line 950, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 135, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 316, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\dist.py\", line 950, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py\", line 168, in run\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\Users\\Kevin\\AppData\\Local\\Temp\\pip-install-aei9kxrj\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\setup.py\", line 206, in build_extension\n",
      "      subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "    File \"C:\\Users\\Kevin\\anaconda3\\envs\\opencv_env\\Lib\\subprocess.py\", line 413, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\Kevin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-aei9kxrj\\\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\Kevin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-aei9kxrj\\\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\\\build\\\\lib.win-amd64-cpython-312', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\Kevin\\\\anaconda3\\\\envs\\\\opencv_env\\\\python.exe', '-DDLIB_USE_FFMPEG=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\Kevin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-aei9kxrj\\\\dlib_a7b71198dcaa4be9a0ebc1a460e45ad3\\\\build\\\\lib.win-amd64-cpython-312', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)\n"
     ]
    }
   ],
   "source": [
    "pip install face_recognition"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
